### ISSUE TITLE
Issues with setup in ghost

### ISSUE THREAD

**Issue by bronestly** [grantwinney/table-of-contents-for-html-page#1]
Hey grant

first thx for providing this. I have been looking for a Ghost ToC solution for ages!

I tried to follow your steps here:
https://grantwinney.com/creating-a-table-of-contents-for-your-blog/

I am struggling with the step:
_Modify post.hbs, near the bottom where it inserts the sidebar, so that it also passes a reference to the current page into the sidebar._

My post.hbs looks like this:
```{{!

	POST TEMPLATE
	- Configuration of this file is not required.
}}
{{!< default}}

	{{#post}}

		{{#has tag="leftsidebar, rightsidebar, fullwidth"}}
			{{#has tag="leftsidebar"}}
				<div class="wrapper leftsidebar">
			{{/has}}
			{{#has tag="rightsidebar"}}
				<div class="wrapper rightsidebar">
			{{/has}}
			{{#has tag="fullwidth"}}
				<div class="wrapper fullwidth">
			{{/has}}
		{{else}}
			<div class="wrapper">
		{{/has}}

			<div class="{{post_class}}">

				<article>

					{{> header_post}}

					{{> post_title}}

					<div class="postbody">
						{{content}}
					</div>

					{{> post_footer}}

					{{> widget_authorinfo}}

				</article>

				{{> post_lower}}

			</div>

			{{> sidebar_post}}

		</div>

	{{/post}}
```

What exact changes do I have to do here?

**Comment by grantwinney** [comment]
No problem, glad you'll be able to use it! I thought GitHub would notify me of issues on my own repos automatically... but I don't see a setting for that. So now I've just gone through all my repos and "watched" them. 🤷‍♂️ 

That blog post needed a little bit of an update.

If you're using the Wildbird theme, forget the part about modifying `post.hbs`. It's unnecessary, since `partials/sidebar.hbs` can tell if the current page is a "post" and access the "document" object all by itself.

Just make sure you reference the `toc.js` file in the `default.hbs` file, so that it gets loaded. Then insert this code into the `partials/sidebar.hbs` file:

```
{{!-- Table of Contents --}}
{{#is "post"}}
<section class="widget widget-text">
    <script type="text/javascript">
        document.write(getTocMarkup(document));
    </script>
</section><!-- .widget -->
{{/is}}
```

Which theme are you using btw? Are you using the default Casper theme?

**Comment by grantwinney** [comment]
If you're using Casper, this might get you started.

Try replacing this:

```html
<div class="postbody">
	{{content}}
</div>
```

With something like this instead. Not the most elegant thing in the world, but basically it's creating an empty placeholder for the TOC, populating the rest of the post, then generating headers for the post and inserting them into the empty placeholder.

```html
<div class="postbody">
    <div id="toc"></div>

    {{content}}

    {{!-- Table of Contents --}}
    <script type="text/javascript">
        var toc = document.getElementById('toc');
        toc.innerHTML = getTocMarkup(document);
    </script>
</div>
```

Let me know how it goes...

**Comment by bronestly** [comment]
Here is my (w.i.p) site: https://ohmycrypto.io/exchanges/ 

I added to default.hbs:
`    <script type="text/javascript" src="{{asset "js/toc.js"}}"></script>
`

I added to partials/sidebar_post.hbs
```
{{!-- Table of Contents --}}
{{#is "post"}}
<section class="widget widget-text">
    {{#post}}
    <script type="text/javascript">
        document.write(getTocMarkup(document));
    </script>
    {{/post}}
</section><!-- .widget -->
{{/is}}
```
It should be displayed after the copyright stuff in the sidebar.
It's a paid theme, but you can download the theme with my adjustments here:
https://www.dropbox.com/s/gldjkigf2izlk79/ivy.zip?dl=0

**Comment by grantwinney** [comment]
Try changing this in the script:

```javascript
var body = document.getElementsByClassName('post-content')[0];
```

To this, since the element that surrounds your post body has a different class name:

```javascript
var body = document.getElementsByClassName('postbody')[0];
```

We'll see if that gets you any closer...

**Comment by bronestly** [comment]
Nope, issue persists
widget is empty

**Comment by grantwinney** [comment]
Hm, looks like you've put things in the right spot. It tries to show it, but somehow `getTocMarkup()` doesn't find anything I guess... I wish the console was showing an error or something.

What if you remove the `{{#post}}` and `{{/post}}` tags from the `sidebar.hbs` file (because I don't think they're necessary), and then right above the "document.write" line, insert a `console.dir(document)`. Check the console / developer tools (command+option+i) and see if it prints anything out.

**Comment by bronestly** [comment]
///edit...seems to work now!
///edit 2: Yep, it works, yet the `console.dir(document)` did not have any effect though.

Thx for the support!

**Comment by grantwinney** [comment]
Excellent! You're welcome. 👍
